routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false
]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/edit', 'AdController@create');
Route::get('/edit/{id}', 'AdController@edit');
Route::get('/{id}', 'AdController@show');

Route::post('/edit', 'AdController@store');
Route::put('/edit/{id}', 'AdController@update');
Route::delete('/delete/{id}', 'AdController@destroy');

app/Ad.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{
    protected $table = 'ads';

    protected $fillable = [
        'title',
        'description'
    ];

    protected $visible = [
        'id',
        'title',
        'description'
    ];

    public function getNiceDateAttribute()
    {
        return date("F j, Y, g:i a", strtotime($this->created_at));
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/CustomHelper.php
<?php

if (!function_exists('get_random_style')) {
    function get_random_style()
    {
        $config = config('styles');
        $classes = $config['classes'];
        $random_key = rand(1, count($classes)) - 1;
        return $classes[$random_key];
    }
}

if (!function_exists('get_random_pin')) {
    function get_random_pin()
    {
        $config = config('styles');
        $pins = $config['pins'];
        $random_key = rand(1, count($pins)) - 1;
        return $pins[$random_key];
    }
}

if (!function_exists('create_err_bag_with_msg')) {
    function create_err_bag_with_msg($message)
    {
        $error_bag = new Illuminate\Support\MessageBag;
        $error_bag->add('status', $message);
        return $error_bag;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'users';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
    ];

    public function ads()
    {
        return $this->hasMany('App\Ad');
    }
}

app/Http/Controllers/AdController.php
<?php

namespace App\Http\Controllers;

use App\Ad;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class AdController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth')->except('show');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ad.form', [
            'action' => url('/edit'),
            'ad' => null,
            'submit' => __('ad.create')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        return $this->saveAd($request, new Ad());

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ad $id
     */
    public function show(Ad $id)
    {
        return view('ad.show', ['ad' => $id]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ad $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Ad $id)
    {
        $user = Auth::user();
        if (!$user->can('update', $id)) {
            $message = __('auth.unathorized');
            $error_bag = create_err_bag_with_msg($message);
            return redirect('/')->with('errors', $error_bag);
        }

        return view('ad.form', [
            'ad' => $id,
            'action' => url("/edit/{$id->id}"),
            'submit' => __('ad.save')
        ]);
    }

    /**
     * Update the specified resource from storage.
     *
     * @param  \App\Ad $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ad $id)
    {
        $user = Auth::user();
        if (!$user->can('update', $id)) {
            $message = __('auth.unathorized');
            $error_bag = create_err_bag_with_msg($message);
            return redirect('/')->with('errors', $error_bag);
        }
        return $this->saveAd($request, $id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ad $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ad $id)
    {
        $user = Auth::user();
        if (!$user->can('delete', $id)) {
            $message = __('auth.unathorized');
            return abort('403', $message);
        }
        $id->delete();
        return ['redirect' => url('/')];
    }

    private function saveAd($request, $ad)
    {
        $request->validate([
            'title' => 'required|string|max:250',
            'description' => 'required|string|max:1500',
        ]);

        $ad->title = $request->input('title');
        $ad->description = $request->input('description');
        $ad->user_id = auth()->user()->id;

        $ad->save();
        return redirect()->route('home');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Ad;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $ads = Ad::orderBy('created_at', 'DESC')->paginate(5);
        return view('home', ['ads' => $ads]);
    }
}

resources/views/ad/form.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-sm-2 col-md-3"></div>
            <div class="col-sm-8 col-md-6">
                @include('errors')
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title title">
                            <b>
                                @if($ad)
                                    {{ __('ad.edit_title') }}
                                @else
                                    {{ __('ad.create_title') }}
                                @endif
                            </b>
                        </h2>
                    </div>
                    <div class="panel-body">
                        <form method="POST" action="{{ $action }}">
                            @csrf
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Title" maxlength="250" name="title"
                                           type="text" value="{{ $ad ? $ad->title : '' }}">
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" maxlength="1500" placeholder="Description"
                                              name="description">{{ $ad ? $ad->description : '' }}</textarea>
                                </div>
                                <div>
                                    @if($ad)
                                        <input name="_method" value="PUT" type="hidden">
                                    @endif
                                    <button class="btn btn-lg btn btn-light btn-block form-control" style="color:gray"
                                            type="submit">
                                        {{ $submit }}
                                    </button>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
                <br/><br/>
            </div>
            <div class="col-sm-2 col-md-3"></div>
        </div>
    </div>
    <br/><br/>

@endsection

resources/views/ad/list.blade.php
<br/>
<div class="container">
    <div class="row">
        @foreach($ads as $ad)
            <div class="post-holder col-sm-6 col-md-4 col-lg-3">
                <div class="post {{ get_random_style() }}">
                    <div class='post-pin'>
                        <img src="{{ asset('images/'.get_random_pin()) }}" alt=""/>
                    </div>
                    <h3 class=""><a class="title_link" href='{{ url("/{$ad->id}") }}'><b>{{ $ad['title'] }} </b></a>
                    </h3>
                    <p class="adcontent">{{ $ad['description'] }}</p>
                    <div class="text-right">{{ $ad->nice_date }}</div>
                    <p class="text-right">{{ $ad->user->username }}</p>
                    @if(Auth::check() && $ad->user_id == Auth::user()->id)
                        <p class="text-left">
                          <span>
                              <a class="title_link control"
                                 href='{{ url("/edit/{$ad->id}") }}'><b>{{ __('ad.edit') }}</b></a>
                              <a class="title_link control psevdo_link" data-link='{{ url("/delete/{$ad->id}") }}'
                                 onclick="delete_ad(this.dataset.link)"><b>{{ __('ad.delete') }}</b>
                              </a>
                          </span>
                        </p>
                    @endif
                </div>
            </div>
        @endforeach
    </div>
    <div class="row">
        {{ $ads->onEachSide(1)->links('vendor.pagination.default') }}
    </div>
</div>

resources/views/ad/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-sm-2 col-md-3"></div>
            <div class="paper col-sm-8 col-md-6">
                <div>
                    <h2 class="text-center">
                        <b>
                            {{ $ad->title }}
                        </b>
                    </h2>
                    <br/>
                </div>
                <div>
                    {{ $ad->description }}
                </div>
                <div class="adcontent">
                    <br/>
                    <div class="text-left half">{{ $ad->nice_date }}</div>
                    <div class="text-right half">{{ $ad->user->username }}</div>
                    <br/>
                    <br/>
                    @if(Auth::check() && $ad->user_id == Auth::user()->id)
                        <div class="text-right half">
                  <span class="title_link control psevdo_link" href='{{ url("edit/{$ad->id}") }}'
                        onclick='location.href=this.getAttribute("href")'>
                    {{ __('ad.edit') }}
                  </span>
                        </div>
                        <div class="text-left half">
                <span class="control psevdo_link" data-link='{{ url("/delete/{$ad->id}") }}'
                   onclick="delete_ad(this.dataset.link)">{{ __('ad.delete') }}</span>
                        </div>
                    @endif
                </div>
            </div>
            <div class="col-sm-2 col-md-3"></div>
        </div>
    </div>
    <br/><br/>

@endsection

resources/views/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger bigger">
        <div class="text-center">
            <img width="40" height="40" src="{{ asset('images/error.png') }}"/>
        </div>
        <br/>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    @include('auth.user_area')
    @include('ad.list')
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <style>
        body {
            background-image: url( {{ asset('images/wood2.jpg') }} )
        }

        @font-face {
            font-family: Eraser;
            src: url( {{ asset('fonts/DSEraserCyr.woff') }} )
        }

        @font-face {
            font-family: Lato;
            src: url( {{ asset('fonts/ComicSansMS.woff') }} )
        }
    </style>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">

    @include('menu')

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/menu.blade.php
<nav>
    @inject('request', 'Illuminate\Http\Request')
    <div class="container">
        <div class="row">
            <div class='sitename col-xs-12 col-sm-7'>
                <h1>
                    <b>{{ __('menu.main_title') }}</b>
                </h1>
            </div>
            <div class="create_link col-xs-6 col-sm-3 text-right">
                @auth
                    <h3>
                        <a href="{{ url('edit') }}">
              <span class="{{ $request->path() == 'edit' ? 'active' : '' }}">
                {{ __('menu.create_title') }}
              </span>
                        </a>
                    </h3>
                @endauth
            </div>
            <div class="create_link col-xs-6 col-sm-2 text-right">
                <h3>
                    <a href="{{ url('/') }}">
              <span class="{{ $request->path() == '/' ? 'active' : '' }}">
                {{ __('menu.home') }}
              </span>
                    </a>
                </h3>
            </div>
        </div>
    </div>
</nav>